version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    env_file: .env
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3000:3000"