version: "3.7"

services:
  db:
    env_file:
      - db.env
    build:
      context: .
      dockerfile: mongo.dockerfile
    container_name: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      mongonetwork:
  app:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on: 
      - db
networks:
  mongonetwork:
    driver: bridge