version: "3"

services:
  app:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on: 
      - db
  db:
    env_file:
      - db.env
    build:
      context: .
      dockerfile: mongo.dockerfile
    container_name: mongodb
    volumes:
      - "mongo-data:/docker-volumen"
    ports:
      - "27017:27017"
volumes: 
  mongo-data: